version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./PDF:/usr/src/app/PDF
    ports:
      - "8003:8003"
    command: ./app
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
