version: '3.8'
services:
  server:
    container_name: pdfast_api_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Mangas:/usr/src/app/Mangas
      - ./Media:/usr/src/app/Media

    ports:
      - "8003:8003"
    command: ./app
    depends_on:
      - redis
    restart: always

  redis:
    container_name: pdfast_api_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
